#ENC[AES256_GCM,data:xOHTjA4MwvLM3upHccj1EB5V852IEecLUporbOSENo8OlV0q2z2zeZEp0o6331bYfHaziT7t7AxcvxlkmGpEXdVp,iv:n4ArUrOIebBG3xV8AgJDOYeD26EtnzT6boZaQcM9P7s=,tag:0j4avilwLDm3m0ScRty4tA==,type:comment]
#ENC[AES256_GCM,data:rVRRSd9AHJc6X/WgrBiqzfznBSFe6E+vEJ/E63PNMcnm9BPwWRucuJpX60niihXs2K83cZvPcuQzA2XxKrq0NzWW0aeZRzX2m7SV,iv:OX1AmNFg/4QdbGJQUAfLndp3JkeTRR9VaI7gDUHbGAs=,tag:jnK57QrNgFs0q5v+wqYsqA==,type:comment]
pve_users: []
pve_storages:
    - name: ENC[AES256_GCM,data:ZXSN,iv:l40WKzWyf7M4N4B57uVaMRZnWd5rwObDXWxUZVSzpao=,tag:Vohlg1GWGg8dHaTEp3SEMw==,type:str]
      type: ENC[AES256_GCM,data:YZ9+,iv:pTRT8uMSkEc3VbUqFAH6cTHpQtlwFiEk9OVGZcFARAE=,tag:PEvz5CZ9HXGA3k2BavIEOw==,type:str]
      content:
        - ENC[AES256_GCM,data:BLuFrK62,iv:zxKkmrNacCSe+PlvpDSWyu+WDa5fVctcZh9/gtQ8Jy8=,tag:ioXFeZZ3zX2/WgjHoyhdQQ==,type:str]
        - ENC[AES256_GCM,data:E1cyIVtb,iv:/dCe/KfDUfRoJgwUG3Mw0FlK5ppPv3EzhXwaJfEim6g=,tag:tmURfxJJ8GGUFOucAPwpMQ==,type:str]
        - ENC[AES256_GCM,data:/923,iv:ltnWo0gFrqxJIXG7Dfv74e/gSVL19ZATcZFEiMLCubg=,tag:rm1RjbBQhwi38OG2mGnJMw==,type:str]
      server: ENC[AES256_GCM,data:aOrmDoJDHmBEvgfF+z4=,iv:e0p/eUKc9+x95Sf5R/oaIyz3RpL6aBRdZWrU9bU7XxE=,tag:Vg4Fc8jmeWdQVXLK46/qZA==,type:str]
      export: ENC[AES256_GCM,data:q+5qoo4GKQ06iuEZhgnO,iv:I/mErjXX9QnPACZ0+djUiwxxXtveMRkDpQcu2TnWHKM=,tag:D1mRTQc0QonFRqrUFIcYYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVk5KNzFudFdRMzl1eldF
            NkxJbUtPMGNVdnJ5aFArZzd3R2dEQk1iTDJzCmt1aFJJa2pJN25hbE1RZE9hRWxo
            Y3FvZmZwUXV1ZkhyQzJDKzlwN1VsNHcKLS0tIEhjNUMrSzk2ekM0N3BGcVBTRkV4
            TGd0UCttZzNuMmZYL2F4L2JCeFJLM2MKthY2OyVde0EOsUf6PJvDAy4hN0u3tsEB
            bLqr0v+XShUC4JKzqSYfWCc7ng6B9a2w0J+sQp/+igGQiyZGd1xIvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTlFHOUVQdHpXTGp2TVNr
            ZzRSVGpPTW5GRnlEWGEvQUxJZ294WTBocWt3CjlMNlBJd0pGSVZWMmUzSDlqVG1j
            ZFJWVGNoNWtUNHd4STR5YUp4T1VvSWsKLS0tIDAzNkMvcUN4dW05S2hKazBhRmRp
            WTBkR3QraEF6U2NUVHdPbTM2RVduWkEK+h9ssKus9s3eBLi1ovrWLz7DlDJN6gDZ
            3Gndyv4u5/lgvdPrRM4SWr1WclfHd89XT1pMo755gy6a6LUiZrE24g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-13T18:04:58Z"
    mac: ENC[AES256_GCM,data:OYdjciW5V7VAUpCCXNmGXH1dhcW4MJ2HO/FlEJKJoZPvfThbkf9x3pOOcsbbuj+29tGQKft9fa1bI5nWeW9KJSnLdNf43um4wQy3LrM3wC1MEy1kSYxeAoLF1vB5R4z5HzaBSf4Pc5pHwGNaLKLARPXsOEhX+Qy8kO0Ybg2Cm6o=,iv:t2LW5pN3jixrJX+etAQH1fo9TJhFYIjMRLl3xx75Ng8=,tag:ZoqUaeonMYT7xLXnt46n5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
