#ENC[AES256_GCM,data:HJ+5+9d24eMeM4O4/jpVR2R4NRNEYEh9mAVPR3wrRrbTOlBFtUesjp958CTNvhJf+aLwX/HZuPPb9mxE4AvwZMqRFThydB+Mr9tKJOLMr3VpQfMgeo/1badAXBpwwWY=,iv:OUOGU6H5RYndhAfwhFMXCW1OSguEAQY6mon21h0ctDs=,tag:aCjHzf4JEOBdRnkZE4YVpQ==,type:comment]
pve_users:
    - name: ENC[AES256_GCM,data:GO3W,iv:TMiPu3IfAGcyw5QoR8jB6I3YcRd5g+AGUNQpA17Ua+8=,tag:doDVeQeIgeiD0hTBzjiUHw==,type:str]
      type: ENC[AES256_GCM,data:wekg,iv:y4509j1QK2bc+zAKUSXdpL7ZHWzt+SS01EjNFTZhEHM=,tag:9DybxFJ35QPDQWOdL6TyIg==,type:str]
      content:
        - ENC[AES256_GCM,data:9Tij319M,iv:fxF8dC6EUgDuOjKCZaUZnflbDf2G0rDEpc3YLXiuwko=,tag:mB3zj5Pnru1e2ErFS5aAMw==,type:str]
        - ENC[AES256_GCM,data:+KkhdDZb,iv:AdqTZY18kPswDRNRI2VJO1hsmz0U+T/mJIgB7gVs2T8=,tag:Dre8MkrP8d/Lpa7sZ4oh1w==,type:str]
        - ENC[AES256_GCM,data:mWy+,iv:iS/tDKjaEiicWsuAgPqKxC1nf1/8b/uC0ltavlCpvyA=,tag:ZlMAkNPwwtphKNw07LbQEA==,type:str]
      server: ENC[AES256_GCM,data:hCEe32hsooBlXYo0vj8=,iv:x6u6UhscCIDzK0oaA+zQYI0bGeSHJFg9DY1iNGO+j+U=,tag:zZ7ZX3G8y1Ny+ClLOl10oQ==,type:str]
      export: ENC[AES256_GCM,data:olXMelmDLfamPhvPVv4v,iv:QTMs/05TMMMJ0IrH471Jv0R+e8NJLeWIDTTrFdz075o=,tag:sH9sf59jQbu4CQBHXyvX7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOEIrZXZGRTNFWUFCMThq
            Rk9Gd0Zub1VBVU01MmxSVkxhc1BEVXQxWFE4ClZCajhLaEZDbW9nd1NZU1ZueXRY
            OE5ZeEg5RWpMdUpNcUpMVFNMVGtNNzQKLS0tIDIyRENhS2ZmLzFzMVgvc2tKQ0E5
            MWdvMzZKQW03VStobmNXZlB2UGlKbzAKpGyncgFi4yy5LyCU/GQM/zR1ayChdheL
            +m6CzCVmeT2oVRztB49woAGO7fN+xP2QZHdwjG4Dl9RN8q5TJiAOkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSXhIR29yR2FsWVA3OEVl
            T2dRUnlJZ1V0QTR5OVoxb05ibUJBSTljWm1JCkZPWVAybXNTSnBTZXZhY2U1b0Fy
            MmE5UkZGdWRrSDlIVCs2R0l6Ukg4Q1UKLS0tIE5wSitZM1VNeDNQVXVnR3NaaUt3
            Sk9Pb2J3VnFxbkN4NzdHRElWd2dTR2sK/IWFTO0kYRsRmHmkeznsOd2oOmKiRHDE
            Ta6utSNNmmEVb1z27lJucOosjZ5OXrxo4elcQ9CYJumn+sVnuMM1zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-13T15:59:19Z"
    mac: ENC[AES256_GCM,data:D82yVUEKTwS7wtMSSPFPWLiY3ab/AsrUJBqzOPnKL8lpmD7ek1vxm7Uaqi2S2PU3hA+haXLFSgj4ItLuRHMC8cXR8CaXpOf7HkOEZcVyDSn5Yk5adrcg/fx2BtaeFz7izUd9zDgCqECRWvVoWsFu2wOUUTGNA9Yv0MuQcnysQp0=,iv:sPd258mhw7GkyNwqTZ7sC4uaG/Q5DY5Raoy1yhyLmlE=,tag:yle2aZd0RX27H9BPEYoipg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
