#ENC[AES256_GCM,data:zQDVulAycK1Uif4IXWoaTJJvvEdPQuUE4aiF+Nlhz2fbqYB/RoTD+w7zXw4KSME5Q8dCsVI8WRw1HkyS0cw1JK6KRFYymr+x+NuLjA==,iv:cbxM1FgXOiJzq3WXaEVXjf+yeSYwrBTU6MGGM6TIims=,tag:06rstO1SXDELWLl9Jy7y3g==,type:comment]
pve_users:
    - name: ENC[AES256_GCM,data:kpgQMu30lGULjGu1ZXJzh2yL,iv:Ai4BXPTB9S1BOknHApupZ3XxfQC5mE8MDzi5dwHAsjM=,tag:1hsnxM8lv9H8OM2udqIXVg==,type:str]
      password: ENC[AES256_GCM,data:cJy5R3nMiFy+G5Ou2F4CZMV5EHHKJCguK0XTY3db2PM=,iv:qM8TbRrZkliddUxxozd3ZCFimm5YlxN708lWYWL3Rbo=,tag:JujAgydK2O7KPfR/JF18vw==,type:str]
      groups:
        - ENC[AES256_GCM,data:uR9p1cTMgMoM9aFO/eEzHHSTx5QhVg==,iv:e3TJtj0n1Tw1Ou6O9PqeD97VTWpCVlWOQ5Y1yQi/cUM=,tag:NhhlxQuRNjgIymtZo/aCOQ==,type:str]
pve_storages:
    - name: ENC[AES256_GCM,data:qm1m,iv:wspjn5huqFlxWyvRLRGGZtODGUCPnJifhFGrjJntD1E=,tag:i5mLDgy21Cff6+C9lBNhaA==,type:str]
      type: ENC[AES256_GCM,data:eu3Y,iv:FMkzUhGKEZ2UJYarbmVE2+NjUkx0MQXns4D6YGuGjoU=,tag:A+qGzTqPDbHDJNqdKczb9Q==,type:str]
      content:
        - ENC[AES256_GCM,data:67XZtX+3,iv:rivTzHqf29zvp0nNhYK0ZLuDNv4S9nhRN89lw9vTnzk=,tag:50IJCh+RzQ52yu6tn45niQ==,type:str]
        - ENC[AES256_GCM,data:8axSx8ty,iv:yh/nFoPSe6s2H/YwEBpExwAcwXolSx0YtyuD8Xa3lCM=,tag:6RKDzIAYrOnN9uoS9iwCLw==,type:str]
        - ENC[AES256_GCM,data:DuW9,iv:VOO6QLZv4ezjh1iHZ7bH0c2vD4TcDzLLEY6imsaZixI=,tag:E1b8KsxschFdwj4Zxti93w==,type:str]
      server: ENC[AES256_GCM,data:VCwB3TIvmtAsXDV5w10=,iv:5KfWxYWgOW5HEEb90B+o4QF1ReqILZ8IyVk0BT5a1vQ=,tag:3ZcipRkDY8SoVbep6bzPKQ==,type:str]
      export: ENC[AES256_GCM,data:NyqgQWSfft01MTj+WR/H,iv:iRqnxlW4RPHoFhGyVZRSrjc/o2BgqZZQ44OFFb3xozk=,tag:u2tqg9AaN8tVz6IAnBlgWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSWNmbnZGNHIxZ0xwM2lE
            a0I5Q1dDN1UzUVVmYUFwTGVMZEYxZDdZUEM4ClNGbERKMDJkdFozMHcrY0ZGYjZt
            aVAvQTlxam02QmM0QUVoYXFpYXlkeGsKLS0tIFNWYzZ2S25CcWhrNFZmTjkwdkNS
            eE93T2NSZzZGUENab3lEUG9SY3pMQkEKxkbXDJUdN9uCAjeOcowAS935j0duH22n
            rzTjESkqm8+1OCTgA9MdKVIbFMxxTRr+QxnhJGnbNck9U6bnhK5a+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN2tmVWtPcmlMWUJqRzAw
            S3d4T3VtMmhQQ0cyWjErSUFPUFJCYWRNRmhRCmhzTWtqRkdhVHZVWG9sSE84SWl4
            VHNpVVFKMzNWYzVpamJJNEo5V284WXcKLS0tIHpmTzJsT3RaeUlrWHVmNGswSUk1
            QkIwZHpiMTRaSWJ2ZGc3eU5yT1k5OFEKQNXnR5D1QvBN4W7vkiKlw2aQ1dnQBLfi
            N3597ZaZO8g0K4PgSllATTMkqX8Hjml8x1sRAKKulJ7BkXnN4/WmIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-10T19:06:01Z"
    mac: ENC[AES256_GCM,data:b4usSvh4ScvPYJLxV1nKJQHaf8m2p4VhbFQ42lj90bifGaPNql34Jg9Aaetv4ZXMDbVyEEZpp2X4uz8QkJDbt/rZh5yWagxA+7cGROIKPEKKxAt1rmR30/bUAf712bwnpiuqpYQoOqoL4ltx39HCfRj1P5VnBOYHd7plTzemev4=,iv:sO40E+C6W4ZNYklf2TMwtUqTy/VZpj6a9CWhRI3xexw=,tag:p6gZXxxQRFyjqqD/YXYgPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
