---
galaxy_info:
  author: P4uLT
  description: Disable the networkd wait unit, for containers only.
  license: MIT
  min_ansible_version: '2.21'
  platforms:
    - name: Debian
      versions: [trixie]

dependencies: []
