---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  project:
    taskfile: .taskfiles/project.yml
    flatten: true
  ansible:
    taskfile: ansible/Taskfile.yml
    dir: ansible
  sops:
    taskfile: .taskfiles/sops.yml
  tf:
    taskfile: .taskfiles/terraform.yml
