#ENC[AES256_GCM,data:AVZ7oDgTuFSi6lUVicP5iNkbbjmORLN2ds//9ly1CKgCicLmKEYSZTY1HtucUKQYi5mVTTH8i2P/7+mDU/Wwwjuwml/i63874sgB,iv:YA4crUBPXwLEziNDVK8AGTM15rr3brAL8krW37vZ9RY=,tag:1H/PDcOKwa1GTEvPkT9TeQ==,type:comment]
#ENC[AES256_GCM,data:53QzrOuHx1PGfZfnsA4hN4KSez0xQOarDimvC2aO6jpiszB9DFqHoNs5fDis/Q6gpd5a47f0z8zfjW6SkKFNZDGhH8GP,iv:DXigyWi0Wm3tedou9oa5qJXOUmeZ7mBMFEjsXMRhNW0=,tag:JSX0Z0tfXOpBwb1oyf8oRA==,type:comment]
#
#ENC[AES256_GCM,data:11flS2sWsg9yS+I3oU+6/iwXL6YEPVMX7uiRxrIt+/UYaTc7c5W1+6AcHxxidKW0UWL8MUTRZ6G4nMQwrz/Wu4I=,iv:7M1msLx9MYMUKOsGpAGRp1+Zm0OTiYSD/e98MpyapcI=,tag:yv07Xe12J1B4CLJ/y7M3Qg==,type:comment]
#ENC[AES256_GCM,data:KmM5/sCSaKuKTkmICcEiG25jcU9ELF4ZotTLt9s5r7MjesIcKkwrvbsYX4empxbJwvFMnoJIBGyy5CqA0LtYdHAa9aUyvLf3DFSUGA==,iv:WLtobJjNEgK0N//VGdB/FJIEmElIsaj2mZfuXtbmLcQ=,tag:7jLUzjotrcwc6qFUTIUhrg==,type:comment]
#ENC[AES256_GCM,data:MRsU/NvK8qhuHPxDoI2+ogHnqXROR6s8LlXG30NixfZBn6oiiq8ESjmUdSHZ6yVPacyzcQTfKmu0WFcCv7MTeag=,iv:MJjzXNMpgNJ0S6uE6EgfWsE4Wbue1E5ht0DnZ3trrqM=,tag:9iLMSnT9v8LNILq0J2hxxA==,type:comment]
#
#ENC[AES256_GCM,data:YqLMwB8N6wy+mV5jh80Ah1Fy4CexsrsltXZ9ieaphOnJzwXP0DdGQAJb09BeUZKBYA4C+9XwV+savtnub/DeHA==,iv:2JrNQkRIUFJ2d3DZ9Ty5LfDd5XxZHmG4hiHNZ7bycD8=,tag:D3OmbmcnzfDwdIV/FQhFJA==,type:comment]
#
#ENC[AES256_GCM,data:FZmmfAYZvtXAM+wOmIhee3ZRPYhccqyIrX5zXQjubT8q4+EN6RocojMgkTqnlgTBBUveRu5Y4hYMz+xNnnKV4VrZsYc3HImU+uwl,iv:266WASxb5Q+vZddsgd2pWEahSj8H53SNDm7WwrhKDm4=,tag:4TOTEp6MFskEoYsmtXCmow==,type:comment]
#ENC[AES256_GCM,data:si1vEA9TszlYOIV7Ozuah92xOVJHajjxZLFPeFSDAwlFUUh9vcLK1fHO0hkdqj0hocw+fw==,iv:YcNw9XzgpishS9wDv74534eC0mhgqEpfc7d6O2Pk2sE=,tag:w12q0TzDEbAfCEXQ4zYfjw==,type:comment]
fleet_users:
    - name: ENC[AES256_GCM,data:BwAafNg=,iv:3EEqP//e0u08KGJ9Ophk+0S1H9vcz+BkWIO5Fm+QG1s=,tag:l6XyTWtYus23CtfX28gqzg==,type:str]
      comment: ENC[AES256_GCM,data:JJSbKzi232wTRNE=,iv:kMtltjMY9X65wA4B6SC+ioOMlzICfuFkU+CcvvTFbiw=,tag:dIm3dh7dKFDHaMawuDwlcw==,type:str]
      shell: ENC[AES256_GCM,data:yf04ef0eJ4+2,iv:DLw8XZf1vhIBWDpKX7wNK+YhhTk/Un3uLul/r99Nu6k=,tag:n2YlaFadTvJDZu4Ca93rnQ==,type:str]
      sudo_options: ENC[AES256_GCM,data:G41b10hsUsNsyuVFdO7E0upqqEd2eNc=,iv:xu0Z4CSM8M4g13A7STPjQB8evgB8wTTrwPPvvLimeWM=,tag:4syk/k73SSTmnmkRI/n9Vg==,type:str]
      authorized_keys:
        - ENC[AES256_GCM,data:bzN3+koxrXYUPnSCmG+xFnaE3a0EXL4NDesqqNNJnYQK9WlY1dwKl2dQ2Y3l7EqnRplSExAQWG8DqKP/g+4/JGKjcm5Lq1oWUGkG1gqhX9U9mTLz4ioRRQzt/jxVURA5LceW,iv:d5toaGES3Gpz8QIjSFJd2B6xEyQ28Lg1YnXZXc7Ll1w=,tag:85EdzXLEoG/AaPSfN2RWcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVVVDZXhsRnlpbjZhbEhu
            dDh1VVdCM2MwU3NjbytNdkZrM1dRemI0akVzClBhKzlPaWMxK3hxY2Rtd1lQbWJo
            ZTRES3RNRHUyOW9YTko3Yk5Dd3VCM3MKLS0tIE1UNXc0TlhRZlY5ZUZNc2xrb1dL
            VDJ4UkRTMmNNSlZhMllXa3E1SVNsQmcKC21qtpZTVOmncQv39HLkGI/5LiEnQhWW
            6wPWIq46UlSOrRyMb6QAnuRMbCvlyN1FrRSVBGLCPLaqmvnFoCcRfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOTJ0L3N4WXd5c1hMbSt6
            TENMRkU0Q1piRDlaWGU2NmI2Q3lTMHdDRkdzCnBST1lsVXNYWkh6dlJtN0RSUkVl
            eXZWVHVRdTd1Mm5MV0VWc0tEa21tbEEKLS0tIFh3d1pqbFBWeEhBcXNJRDZnL21E
            SmRqYmo0ckFvdGlSYnc1Vk9jNWEwRUkKKD6kz1gBFmLFd/Y+gV28soh0QqL2ABFH
            Si5331SQE59cm3DBIpJcYe4fT3AWGvoPe3wYzSyFbjijO1poylVqfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-15T18:35:53Z"
    mac: ENC[AES256_GCM,data:20Cc2ACprM1B39vyUmGpDz90KuuHefbgB+gOvCS7n/YnEPvVegy8ZGOPUIeGoAlvI3mfX8ya3037eC/6bsU3DrwKNEADhYT2BHn926JKgQmVFpwTMxncbo56lcr+r3xqIiZIznoYwnQEb6ktgcNcaoZDLy9cljfXgSqoXP+cZFA=,iv:41+gtypeeezW/LTSee4/YJA9ocTSYS1+Aw87Ej9b0YE=,tag:0TojEysOxmc0h/HbvClJXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
