#ENC[AES256_GCM,data:o0EcMLGwubA1cRLnLKAh9zWzi0Pmki2eVCPvFICPhoFwnMBSiVM5VG1aue2TYAB/QRCmFhHwwKrKjmp9Q2MThMm3q202XE8tW2dx,iv:QJ4UbxAHkugDJsP7b8O7B6L0h3S9WZP9DgQkj/EPBzY=,tag:fw8r6EkhZAp2Ihy+1A5jgg==,type:comment]
#ENC[AES256_GCM,data:fIXYAcoUjuz1LL8RYHJUMCkQPItHRmD6CXl/lks6tehAOWcIuNqajtVr3rzmbeBSxWxIMyRlTPJJGU8XSpLAYPoVMze7,iv:XZkLH5LhwW1HaJEIT5Z+xIMPU6lrX2Yv69C0wSxCXCg=,tag:IldPBV9M6Pc5wYp/C+LTQA==,type:comment]
#
#ENC[AES256_GCM,data:tZPuGgLa+dzXaGKcBf8WklYNp0cilDkxjECJfO+zd2zatyXed/8zj+sdhUXfBusQz9deYTPi40nR8ULyk3tpQ34=,iv:g3LIahNWo0oT0CoGrPlIPMnjGS748VH3qFnNZjkgHr8=,tag:h0/lmsz3q6zVg+aeX+/s8g==,type:comment]
#ENC[AES256_GCM,data:dzjtw5lkfLwy2D9rE5MlcT9xUvSeuI6zWNZgo4HZMeu6zrkTlOwNppTwu1VQQVaCxywToioIcLgwoZsIUU5kbCEualS6Kne5ybiY3g==,iv:dqObsjuJQjNJFS3D9dNNzN1EPx/N6ZSn0qeOCmpF5r8=,tag:XYfjfgUPS2U/GprU1kbpYQ==,type:comment]
#ENC[AES256_GCM,data:5sQwz62RldQw0kSD6hchIyH7NKdATsCncZuuO1vNOx8Upl/oPv8kQeuumR9AD8Su3ir2JF8zqmtZTxsdg0l/EzA=,iv:0mo3UkpnWLgAI99t4zmaTRu0F4WBZaRn4Bj9gKORm0s=,tag:ySRDAVbJVDsaR08JO78+zQ==,type:comment]
#
#ENC[AES256_GCM,data:F9QqxKIes5sD54TQIvcDZfIzS2cEMs/fLMx/xIh5OkqJo0hA+1tn2ZVqjI8odW2jEmChhgloEJOZr3eDyYp57A==,iv:ZCUTFR2wvtGXCKcSddM/FU00INQHHVYbQTImaJj2GsM=,tag:lpfs2qvLsMxpiNmXYAhx+g==,type:comment]
#
#ENC[AES256_GCM,data:vbmyq+3tdQP6hCS+jIrEenNiyMFqhr6w+Eb3+L1+TecFBhaRMg4fEzH3RUDn5sTs8VozUJUAFpLOaBeiZ+KO2CsKGFu2BQz1g9wG,iv:wr/bV2RR5JBRfu/R8UCEyv3DfMA9EQp4h0v1ejQktzY=,tag:3LmVAmZD+mkhoXkT+LkznA==,type:comment]
#ENC[AES256_GCM,data:KUaj7MFOUsuy+lK74ip/Nu4zrC5Hv9bq2nYzcHuxcMQDNBZS7fvY+dSxo8yfHUteyTlSXA==,iv:rDzWhzMFTIaiGvMWj0HZ1xMaN8wc9GAdcD13Zp9B0oE=,tag:ezH5EiokNVc7dxdk2tcLFw==,type:comment]
image_users:
    - name: ENC[AES256_GCM,data:3oMZfjI=,iv:Ej25Dm2Wgd0/0XQ+ifMfl1OBe7v4gKGQEWFNCL5DbrE=,tag:W/YltwCn2GNTC8/q5M4G1w==,type:str]
      comment: ENC[AES256_GCM,data:gRIbL7WiJadkHTI=,iv:2iyGsNd8aQVm/tXUjKvKuyt5ttB0IrdF/BaFWHXFHWM=,tag:0bM8X+MXzCo2KlgTHwv+kg==,type:str]
      shell: ENC[AES256_GCM,data:4ShoicJ21dzh,iv:eASIhZZG/wgY8ABxfCPcYOHfZ9/AzQz138OddTvhthE=,tag:hDJbvgaDytq7Bl2c46IMSA==,type:str]
      sudo_options: ENC[AES256_GCM,data:eWT0rClL1/IbqsR4ivbXSBxDjmQHkIo=,iv:ehF02aofGFhrR5U7i1tYzZeXLMtEZsRQkc/uZkZyJ/M=,tag:dVztuZe3da+FGniLNGYSWA==,type:str]
      authorized_keys:
        - ENC[AES256_GCM,data:dquJEpJbVK/l75yGZIj5X/+jdaWF93fQPcgCiwVQn9lMYNEESpFpHWhfI65y6/kMUWE0QxAbn4d1Jw6xIIb+Gsx7tRviM76/akSZQ7qSSJ/qtGaYT651jdVzZdIy1Z/CXw2y,iv:cxJNYV+9ahPgu3nCh1LduWKX0fYxHumy7kPCVKt9e1Q=,tag:y0P7tE077sL4H+ccyNJfJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSGxSVW5VckZycUwvOTcy
            K1pqYXRXOWtLNUQ5aUlMNmdxRXNKVjdaOXpBCkNuYXZ6aE1VOS9hYzd0d0dOMWFZ
            VHF3T0Y0dWIrU2dwK21wbDlOV2dHaE0KLS0tIDZkSGs2eXZtc3VqdmRZdG9PalF2
            Y0g5dkpHK2s0MXhqNGViWjMxbUNaOXcKe7VJMmqYOMfYXaESomSbW+KEO6Tsb4AO
            5RTk8NeA7oaJTHBfjg/ni7/pDNkf3zU09DkLNoKWfjjhMOxfRFk5Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ1lRazNScFluZUZyQWNS
            akJNQ21EakdUVUtla2IzUkJSRXByUGJ3eHg0Ck9IUkI2WnFKTktLV242Sms0SDYy
            R2QxN1dKc3MzbVpTcnlpcm1GMEo0VE0KLS0tIGNRZEVSTFl0WWlUQjVlVy9hbE8r
            a1VpRlIzQTBZcWgxSWJnbCtKeUgrVmcKp/ZSNxzvY1d6p/I3nWaAEmNnibrVrqM7
            my5KTxKVu3bHahNJbKPQo9aEVY15M40e8djUIjFJVvVHpbhbP8wrJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-15T13:10:38Z"
    mac: ENC[AES256_GCM,data:SvG2RHsBgMX6c6O0J5OeDW/oXYaAcD6pD6Upn/NG2/3TxI6eQcfM1UO/CrG0dLGvcb2YZn74GFSaLned9E80e94YDXXoG9Rdlc6yxxnOAkVhwijaQXQOo1zLKYOIcbJLd8pQfvtjfrPONQfHexrowl8Vvk7hSGr+LhNKSfHgY88=,iv:3+o7ecA1Fj4LxDvHNqa1C4knJEAsrddS4Ap/SywUdu0=,tag:X7R/NFeX6wHLSniOMJ4V6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
