#ENC[AES256_GCM,data:QOZAX3Fqp1N5adKtvQXw83rYZ62qNQRZ6XlbxEKnYrLNnVySHLKFYQ7mYKrCIUGQskC11SdhZSroY9vIKqs=,iv:ZdDMWKiyTS74t7y7evE+vcbmQ9oosK6JKVzCUbKP2I0=,tag:Ik5Vw2lhQmxdSG/2Oov/WA==,type:comment]
#ENC[AES256_GCM,data:J6HHWIZrIayObnTpXuYEMmwX8PrkOCqIHOzt/rzdClctaKH2w01dzFP3TZreBabWqfZOYtwEFP26QRqbd1mSXWw=,iv:x+8FEJTuBMLG8dc6VMtuf7gXoaUrHehA1MNJCqGl70U=,tag:83DoVIf0kL7bMGLNu1giug==,type:comment]
#ENC[AES256_GCM,data:R01Xbod59wgykEKYIMSpFvHiThCUjqfS0i9mIGs=,iv:59juMIg6BcyKIUB//y/BG1R+31h61jy9bcspH6yDNUA=,tag:R3R2oQvWkus4tXg2YuJTog==,type:comment]
ansible_host: ENC[AES256_GCM,data:5LtDD7cQut4I5hzCdOE=,iv:Hu+FJGaUnTo/L9tKYauie4xprfk/bNpr/L2b+BzqATQ=,tag:ijnmbQmkZgycdqj+/Ah3Pw==,type:str]
ansible_user: ENC[AES256_GCM,data:0SBcog==,iv:yoIdCw1tUWb9aPsn2GCtpswlWQ2ZfvVzxMVMFqWdjxw=,tag:Qzq/wl5pIfymhJEKChWNEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkM1Z25TUXJ5bCsvTjVN
            YUlWRGR3TXA4UHNpMkUxS2Z6bFk2bHlPN2tBCkF2TkNPR2hQUE44VjhYNEhQNXA1
            TWtQdi9MYlRTM0dFQWZCQ3A0eGtFK3MKLS0tIFBCSmZuUWUyNFpQNlE0Ry80Q3B6
            RkxhYjdzczh0aXl6TnBoaDJFWUVjc1EKJnY+3bB136W6o2O004SSeLX5Gjzc+1th
            RV18yYCaXY2ZTX8q6CjM4avTyP64vh6Fa25LLhcSHIAiLUUC7u18sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RGJrWTVVblZVWXUrb3dK
            eEYzZDF6aHVWQUtZcE91L1JEb2NVMkkvL21rCjVraFJxRHpHWGE0Z3gzZEU0eGR2
            T050L3lVaDF2TFdjcG0wS1BBdDEyVFEKLS0tIG4wRWZteXBlZ1YzbDB0MVRxdGhU
            czhTemE2SFRWUDdVbTBJTEw1S1BJL0kKskcYPYtnL2PDrRT8Co4zO/MVKSAPqh9H
            Vht2pB6SMqseLaRncuJvwFGRINvE840vXIfVEV2J0ez4xTPIuXV8mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-10T18:37:02Z"
    mac: ENC[AES256_GCM,data:6Cw3+Wej1UUnXGKd4DoUHPRld+ZJGR+TSyYzhn9YvM3Ehk58HyyYGhaQATo2qzDX7gBWsyPY+muDC1ejfmKcKAr8UzGbkrIpijE2FSJQqM8DGUVhACsHma0dnp1lb8mJ/vU/MR1zQobxwVWBwwWVfP8kZ5GJmC5og6NPEkMILig=,iv:9KIN8Ec48Y0K2rt0CyZwRWQ/mxIPNaUgRfGEpmjGoIA=,tag:Q6sgRNHTYz+tIb6+yuYYrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
