#ENC[AES256_GCM,data:FH8AUaQvlGGB6dIy1SULZaUjxT6/s3LGqnxWk44Ie2fdFe3sOmRIRxS9Fq8DiL85wjAwk2M2mkeLMVUjfZukHWlcxHXBrw==,iv:xWwM4gV7aBXimfwW7BKi8d15Xt1gV+AXwOjEhx8zfqc=,tag:VOD+xvz1pcWVmzZRiKY1mw==,type:comment]
#ENC[AES256_GCM,data:8Et9ySZoEfjhP6DaYvc6DHFSMWirzu53IMdO0xOzeHYXI01WLYMYshO33Px7S+CESRWqdNQRf6gBjCxwLY8=,iv:T87G/69AwHP7OLOZyJo8+Mf4X3EvQlc9rUNkfvXmxKU=,tag:iXU7hbHv5m/gcZ3BI3I5LQ==,type:comment]
sops_canary: ENC[AES256_GCM,data:pRD6buhS1NMaMCqT,iv:LV8LbomMTKinoxpXO2/bpcNMQy3beSfklkP8FTGhl8A=,tag:iLDzs8Dm+OhECSuWva1oLg==,type:str]
fleet_users:
    - name: ENC[AES256_GCM,data:TsAe7Kg=,iv:O9wUXRAS9CC9tNW7yqcrGsqGylmmCQpHh5bP+PDJZy4=,tag:MzeIBfJhIvXEO81W8FV/zg==,type:str]
      comment: ENC[AES256_GCM,data:yjjbEm4o9g3sfvw=,iv:XH0xX2s9rEkHRwzaiTeGGAdaLdercvBFvG0xIg3gUWg=,tag:bkQR2MJiAoEKPzVbOYnn3A==,type:str]
      shell: ENC[AES256_GCM,data:6hl48yT6swTQ,iv:pEWu5nilUtNueqi1ptpw1MIleVwpn6SUhVd/McS7nM0=,tag:5uB1tLv91SgOZx7u8kwMbw==,type:str]
      sudo_options: ENC[AES256_GCM,data:/JG/cWKa7fDj5U1hmA/p4DU4Bvt7fWs=,iv:bfOfwJE4MRpuPH3Qh4jxuCd5NnRdVgxFOMHfquK00ho=,tag:4F64IojbOCmDQMCRgGffLg==,type:str]
      authorized_keys:
        - ENC[AES256_GCM,data:uVjQy+rtg6nbB0eCbgBtUFMb5EktEK/InBqwbdGAXM6eMEFq9PYT0dqMoHhYnPpKHlwH+ixt/vTv4IrD/9B3675TQ9oofhqoRWo2E4GxOfOxNfTNkETgGzNbla+1LEKymdtF,iv:aAuWF67T8px6qwc4Dp1vPM+ZlTr1uyD5fmNjlXaW/Eo=,tag:vygm3hcf+MEDqd5NzA6Nxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNjJzUDl0ak5rN01sbUNv
            eElSdklEV0J1SFM0c3dqNmhrYXNja1B0ZHprCkpDZy9zc1RlN3ZvdFFsZU9tNUM4
            R2tQbWg5SVhSUU5DL1graE5sc202ZFEKLS0tIHI0RHcvYXRxdm1ieGpxQ2FjTnV0
            MER6NmFHMlBlUzlDK1lNOEZUQ0YxamsKxbALTQdZ4qqnkVTFZ4mI+wJuTHQ406fL
            mItg9cX0mM+WI5UvebKHyG2AzeRvFlO5lIUyUul0/s9YmQjpT3DSCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVENEVFZxV0Y4U1kvU3Iv
            THVqNFZjMXkzRkVIR2ZKaEdHQ0xqdm9EZHh3CmlzYVhCVTZLdkNsS0Q1alZMcGhh
            VE5YQjJVbWd1RElyMklhN2QxNm1qVk0KLS0tIHJ6UnN0RjRqRlR0K25uaENqK0pu
            Z0o1TTB2QWdybHI2OUllZ2hYOHhWU2MK0iWveK6eD2Jul9wcMdFkfHxP/nUS3hHZ
            Vw1/3piVB+0SFSR4HOjvWbjBwwn8np6PNEKtJHTi6cO8nME8QBvUXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-15T18:36:22Z"
    mac: ENC[AES256_GCM,data:fBPjuqPZPWF0/UkLrTBjv63MbF7YRdAW/oExsdcRtX3Ae7wn29HLFB2SBBEEDm2qczQ5gSifz31NDL/65lkRHQ1MhHPD3ZtvdFWco3hXfI1zkHRu51UEr4iCozWFtk9fAEVw2rVeudrj3Em+ntrWDOLUEn80Mvh8Vv+FNSExbd8=,iv:R3LHVOKSmLOYJjoW4ujWFi5BJ4pRivWIOVXpAESgASQ=,tag:guX+EDehHO7S7CnuHn8Asw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
