#ENC[AES256_GCM,data:f1zOBTUN55kY8Woyt/exBN+UuQKqd6ZSh7GlS+4rxkTPpTK1/xlMvfnpcrYyPv3Bp6A+N6V36tTx3sKSIcrH6ryhIIT0KA==,iv:oTYkadNWXr81+yByMzeduDPBVP68M5GkcVxvVLJZDSc=,tag:aGiYJ8osfUFiBfDpU3nMig==,type:comment]
#ENC[AES256_GCM,data:BkBJatdYXM3FtEpm+u6jCUh7BOs8gxWeWL2ujSp8dmrKMC1RZIvEaXFjoUUOKEZiHB4Vt7yycdc6JLPe0jk=,iv:EMYe9v4+ugC1YsaPl4M/tGUaNDNy5AaDJSy4snxPKBE=,tag:mzkULzlAi+I3RJkYsgbfyg==,type:comment]
sops_canary: ENC[AES256_GCM,data:4ODuwg8xjw4TWssF,iv:aUkDoTXTd3MqiO0hqpVZzAXNZOB5Wh9I4xJEwMRII1A=,tag:jaL5qOnq3i7y9cg2EY1h+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K29DZmNuMHJZdnhMTXJh
            bDFYaWUyck1XYy9GWDdwOTJMSnpDVXA5TWlvCll3c1dJd2xaUGtLOGVTRm04NE5G
            T3ZhT25iR0EyNG5yKzRkdnRZbnFXQU0KLS0tIGNXUVFqR0FpVVhZUDBPeDhtTmxF
            T3VsYUk2QXhnSXNiM1VRRlo0Ynh5QVUKU3ky2Kig9Wjt1wBeWcziaH7MI938q9QH
            LTeUDewouGgnIFA7e7MQavGYqiLoCH5be9QdDn2lB9N0YfTdsFgWNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9ywveleuhdmarr5tua75gryzmpts244s39q7urh5qkmda3h4c0qa7nz72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSHlsNWJleFlOM2l5M0F6
            Unp2MGtLZThCbTBaSzNSeC9NUlVuaGRGRmhBCkdDamJ5TmNJWlhtVjJhYXNwSHoz
            aSs1ZXVqMFBrM0c3eUxUb2tsZXpSNHMKLS0tIEZpMlFCWmZseTBtNE55dHZHeU0x
            SzNvSzBtR0dYb0hWNXoxclUzRklxaEEKDXOdiTwGc77o6L8nXMupiNXJs7h7Qj90
            tgUqt4vDSBHzFOIi+Lyp2ZiO8Ufa1XWMpoPdpzGLLV8FCWryoIFqCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eg5jzz6fhl64vprwp8rlwn0hmgllqcnjafav2myrpr3unqq4zarsyn78ks
    lastmodified: "2026-09-10T15:52:37Z"
    mac: ENC[AES256_GCM,data:i6aBkCQ7ZmKzxhr8ltOWT+G1hYRtiL/8+iUl+yVimUZi6DmgjYRZ3b4taAHF+ji9Gf1aoaSFUva3DKoMjklUPS86sSqgO+nh0LVfrZIhd3aYyJ/27+FLTLVlGaXshIfgWbRT0ImZOYD7iFxNfwBlS7ngMPImIcuMrURqraoNaZg=,iv:LxD3eREfndwQIMRo06efMUaadJ6IJSCxkhzUz8g8Tqw=,tag:iy1igcjAXT4/aplTuh6WlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
